name: Android CI Workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Run Kotlin Linter
        run: bash ./gradlew ktlintStagingDebugCheck
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      #- name: Sign artifact
      #  id: signArtifact
      #  uses: r0adkll/sign-android-release@v1.0.4
      #  with:
      #    releaseDirectory: app/build/outputs/apk/debug/
      #    alias: ${{ secrets.KEYALIAS }}
      #    signingKeyBase64: ${{ secrets.KEYSTORE }}
      #    keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
      #    keyPassword: ${{ secrets.KEY_PASSWORD }}
